### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by brunobell** [RoniRengit/Job-Crawler#2]
maybe you can try .gitignore in your git directory, which will ignore all temp files when you try to push to your github repository. good work, good luck :)

**Comment by ronirengit** [comment]
Hi Broono,

Thanks for your mail.

Those are not temp files.  You need them to open the .exe file.  I used
Pyinstaller to convert my python file to an exe file so that it can run on
machines which do not have python installed.

Thanks and Regards,

Roni Rengit
On 27-Apr-2016 10:39 pm, "broono" notifications@github.com wrote:

maybe you can try .gitignore in your git directory, which will ignore all
temp files when you try to push to your github repository. good work, good
luck :)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
https://github.com/RoniRengit/Job-Crawler/issues/2

**Comment by brunobell** [comment]
ok, so it seems you were bundling to one folder instead of one file (what you said in your reply up here). if you did intend to bundle to one executable file for windows, maybe you can take a look at the official pyinstaller manual here : http://www.pythonhosted.org/PyInstaller/#id21
anyway good try :D
